### ISSUE TITLE
Suggest using cKDTree

### ISSUE THREAD

**Issue by adehecq** [VAW-SwissTerra/SwissTerra#1]
If my calculation is correct, this array would be 2e4**2*8 = 3.2 GB for the whole data set, so it might not be ideal.
Using the cKDTree query_pair function could be more efficient: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.query_pairs.html#scipy.spatial.cKDTree.query_pairs

https://github.com/VAW-SwissTerra/SwissTerra/blob/d10122503c3649aff563da8414ecc01628b7b2da/terra/metadata/image_meta.py#L161

**Comment by erikmannerfelt** [comment]
Thank you for your suggestion, Amaury. It was even worse than you calculated: the script crashed after filling 120 Gb of RAM (a memory leak I guess), so it doesn't run at all. I assume that your suggestion might be a much better approach. Since said function is not used anymore (it was for the deprecated ASIFT), however, I will close the issue for now. 

I may reopen it in case the function ever gets a need in the future.
